### ISSUE TITLE
Would it be possible for you to put into a Google Colab notebook for beginners like me?

### ISSUE THREAD

**Issue by zanderbush** [uhh-lt/par4Acad#12]

**Comment by seyyaw** [comment]
@zanderbush  which functionalities do you like to have notebooks. @gopuvenkat  might have some of them already!

**Comment by zanderbush** [comment]
Thank you for responding! I am most interested in paraphrase generation, but I struggled to properly set it up last night. I figured out how to insert it into google colab, but I now realize that I may need to clone the repository first. Is that accurate?

**Comment by gopuvenkat** [comment]
Hi @zanderbush!

We have maintained the paraphrase-candidates-generate.ipynb notebook in our [repository](https://github.com/uhh-lt/par4Acad/blob/master/resources/paraphrase-candidates-generate.ipynb). This notebook expects you to have the following datasets/resources: 1. [Beautiful Data](https://norvig.com/ngrams/) 2. [COCA](https://www.english-corpora.org/coca/) general list 3. [ACL](https://acl-arc.comp.nus.edu.sg/) anthology corpus 4. [PPDB](http://paraphrase.org/) MySQL database and 5. [GloVe](https://nlp.stanford.edu/projects/glove/) word embeddings. From the ACL anthology corpus, the token frequency counts are computed during the resource compilation step.

paraphrase-candidates-generate.ipynb generates the file which can be used to perform ranking of the generated paraphrases. TensorFlow Ranking has put up a example on [Google Colab](https://colab.research.google.com/github/tensorflow/ranking/blob/master/tensorflow_ranking/examples/handling_sparse_features.ipynb).

Thanks!

**Comment by zanderbush** [comment]
Thank you!
